dependency:
    name: galaxy
driver:
    name: docker
platforms:
    - name: instance
      image: ubuntu
      groups:
        - rhel
provisioner:
    name: ansible
    log: true
    lint: ansible-lint
    playbooks:
        converge: ./playbook.yml
verifier:
    name: testinfra
    directory: ./tests
    options:
        v: true
        sudo: true
scenario:
    name: default
    test_sequence:
        - lint
        - destroy
        - dependency
        - syntax
        - create
        - prepare
        - converge
        - idempotence # This will rerun converge to see if anything is marked as changed
        - side_effect
        - verify
        - destroy
