---
- name: Install Postgres
  become: true
  hosts: instance
  tasks:
    - name: Install PostrgreSQL
      apt:
        pkg: 
          - postgresql
          - postgresql-contrib
        state: latest